name: GitHub Release Action
description: An action that creates GitHub releases
inputs:
  title:
    description: The title of the release
    required: false
    default: '{version}'
  changelog:
    description: The path to the changelog
    required: false
    default: CHANGELOG.md
  asset-name:
    description: The filename of the asset to upload
    required: false
    default: ''
  asset-label:
    description: The label of the asset
    required: false
    default: ''
outputs:
  release-id:
    description: The ID of the GitHub release
  html-url:
    description: The URL to the GitHub release page
  upload-url:
    description: The URL to upload assets
runs:
  using: node16
  main: dist/index.js
